<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_65984</name>
   <tag></tag>
   <elementGuidId>266de3d7-2bc7-4189-9126-864b49539d7f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.InovuaReactDataGrid__cell.InovuaReactDataGrid__cell--unlocked.InovuaReactDataGrid__cell--direction-ltr.InovuaReactDataGrid__cell--user-select-none.InovuaReactDataGrid__cell--show-border-left.InovuaReactDataGrid__cell--show-border-bottom</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/section/main/div/div/div/div[2]/div/div/div[2]/div/div/div/div/div/div/div/div/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>dda5e314-e322-494b-b987-ecaf2d5af101</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>InovuaReactDataGrid__cell InovuaReactDataGrid__cell--unlocked InovuaReactDataGrid__cell--direction-ltr InovuaReactDataGrid__cell--user-select-none InovuaReactDataGrid__cell--show-border-left InovuaReactDataGrid__cell--show-border-bottom</value>
      <webElementGuid>01f3c83d-ff5a-4fab-837a-8ee55c6930d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-props-id</name>
      <type>Main</type>
      <value>no_customer</value>
      <webElementGuid>26dca0fa-0327-48e5-8868-23bec3022934</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-state-props-id</name>
      <type>Main</type>
      <value>no_customer</value>
      <webElementGuid>7d88ef2d-b42b-49e7-a573-cd99275cc7ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>65984</value>
      <webElementGuid>6e1385a6-7519-4978-b3ba-6fecd859b52c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/section[@class=&quot;ant-layout layout css-p8cx3h&quot;]/main[@class=&quot;ant-layout-content&quot;]/div[@class=&quot;site-layout-content&quot;]/div[@class=&quot;ant-card css-p8cx3h&quot;]/div[@class=&quot;ant-card-body&quot;]/div[@class=&quot;InovuaReactDataGrid InovuaReactDataGrid--theme-default-light InovuaReactDataGrid--columns-ready InovuaReactDataGrid--show-hover-rows InovuaReactDataGrid--direction-ltr InovuaReactDataGrid--no-header-border-right InovuaReactDataGrid--cell-borders-horizontal InovuaReactDataGrid--cell-borders-vertical&quot;]/div[@class=&quot;InovuaReactDataGrid__body&quot;]/div[@class=&quot;InovuaReactDataGrid__column-layout&quot;]/div[@class=&quot;InovuaReactDataGrid__virtual-list inovua-react-virtual-list inovua-react-virtual-list--theme-default-light inovua-react-virtual-list--virtual-scroll inovua-react-scroll-container--block inovua-react-scroll-container inovua-react-scroll-container--theme-default-light&quot;]/div[@class=&quot;inovua-react-scroll-container__wrapper&quot;]/div[1]/div[1]/div[1]/div[@class=&quot;inovua-react-virtual-list__view-container&quot;]/div[@class=&quot;inovua-react-virtual-list__row-container&quot;]/div[@class=&quot;InovuaReactDataGrid__row InovuaReactDataGrid__row--direction-ltr InovuaReactDataGrid__row--no-zebra InovuaReactDataGrid__row--no-locked-start InovuaReactDataGrid__row--no-locked-end InovuaReactDataGrid__row--show-horizontal-borders InovuaReactDataGrid__row--rowheight InovuaReactDataGrid__row--first InovuaReactDataGrid__row--last global-custom-row&quot;]/div[@class=&quot;InovuaReactDataGrid__row-cell-wrap InovuaReactDataGrid__row-hover-target&quot;]/div[@class=&quot;InovuaReactDataGrid__cell InovuaReactDataGrid__cell--unlocked InovuaReactDataGrid__cell--direction-ltr InovuaReactDataGrid__cell--user-select-none InovuaReactDataGrid__cell--show-border-left InovuaReactDataGrid__cell--show-border-bottom&quot;]</value>
      <webElementGuid>3c9eb7ed-e8d9-44dd-bdd1-5dc3973dbf30</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/section/main/div/div/div/div[2]/div/div/div[2]/div/div/div/div/div/div/div/div/div[2]</value>
      <webElementGuid>1061f7df-0892-4004-86c2-c923546b9127</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='OH070923004'])[1]/following::div[1]</value>
      <webElementGuid>fd787808-54f3-475f-a56a-145cc94e1e79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Operator'])[1]/following::div[18]</value>
      <webElementGuid>640d14de-ae3e-46b1-bd1a-e131c317e2f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TESSS TIM IT'])[1]/preceding::div[2]</value>
      <webElementGuid>e6d89a15-b9d1-4601-8e8f-1679a3e84ec1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ella'])[1]/preceding::div[4]</value>
      <webElementGuid>e6e2c940-9aed-4d20-81b3-24dfde4c4963</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/div/div/div/div/div/div/div/div/div[2]</value>
      <webElementGuid>f8135f2e-f852-4b7b-afd3-d9d357d60310</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '65984' or . = '65984')]</value>
      <webElementGuid>49b6386a-90c2-431c-a3c9-71b022356104</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
