<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_OH070923004</name>
   <tag></tag>
   <elementGuidId>d7ed755d-4842-496a-b3bf-41c6197f471b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = 'OH070923004' or . = 'OH070923004')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@class=&quot;InovuaReactDataGrid__cell__content&quot;]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.InovuaReactDataGrid__cell.InovuaReactDataGrid__cell--unlocked.InovuaReactDataGrid__cell--direction-ltr.InovuaReactDataGrid__cell--user-select-none.InovuaReactDataGrid__cell--first.InovuaReactDataGrid__cell--first-in-section.InovuaReactDataGrid__cell--show-border-bottom.InovuaReactDataGrid__cell--active-row-left-border</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>02708e75-aea1-4000-96e9-4bd806bdf16a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>InovuaReactDataGrid__cell InovuaReactDataGrid__cell--unlocked InovuaReactDataGrid__cell--direction-ltr InovuaReactDataGrid__cell--user-select-none InovuaReactDataGrid__cell--first InovuaReactDataGrid__cell--first-in-section InovuaReactDataGrid__cell--show-border-bottom InovuaReactDataGrid__cell--active-row-left-border</value>
      <webElementGuid>9655a180-c9fe-437b-8c35-35e87a0687fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-props-id</name>
      <type>Main</type>
      <value>no_order</value>
      <webElementGuid>1e6c8b2a-5d98-4318-9d26-728c17a85336</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-state-props-id</name>
      <type>Main</type>
      <value>no_order</value>
      <webElementGuid>4c8a5bb2-e6f0-45f6-944a-5d36d050364d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>OH070923004</value>
      <webElementGuid>00781f58-310e-408c-a08e-93214a3eb7e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/section[@class=&quot;ant-layout layout css-p8cx3h&quot;]/main[@class=&quot;ant-layout-content&quot;]/div[@class=&quot;site-layout-content&quot;]/div[@class=&quot;ant-card css-p8cx3h&quot;]/div[@class=&quot;ant-card-body&quot;]/div[@class=&quot;InovuaReactDataGrid InovuaReactDataGrid--theme-default-light InovuaReactDataGrid--columns-ready InovuaReactDataGrid--show-hover-rows InovuaReactDataGrid--direction-ltr InovuaReactDataGrid--no-header-border-right InovuaReactDataGrid--cell-borders-horizontal InovuaReactDataGrid--cell-borders-vertical&quot;]/div[@class=&quot;InovuaReactDataGrid__body&quot;]/div[@class=&quot;InovuaReactDataGrid__column-layout&quot;]/div[@class=&quot;InovuaReactDataGrid__virtual-list inovua-react-virtual-list inovua-react-virtual-list--theme-default-light inovua-react-virtual-list--virtual-scroll inovua-react-scroll-container--block inovua-react-scroll-container inovua-react-scroll-container--theme-default-light&quot;]/div[@class=&quot;inovua-react-scroll-container__wrapper&quot;]/div[1]/div[1]/div[1]/div[@class=&quot;inovua-react-virtual-list__view-container&quot;]/div[@class=&quot;inovua-react-virtual-list__row-container&quot;]/div[@class=&quot;InovuaReactDataGrid__row InovuaReactDataGrid__row--direction-ltr InovuaReactDataGrid__row--no-zebra InovuaReactDataGrid__row--no-locked-start InovuaReactDataGrid__row--no-locked-end InovuaReactDataGrid__row--show-horizontal-borders InovuaReactDataGrid__row--rowheight InovuaReactDataGrid__row--first InovuaReactDataGrid__row--last global-custom-row&quot;]/div[@class=&quot;InovuaReactDataGrid__row-cell-wrap InovuaReactDataGrid__row-hover-target&quot;]/div[@class=&quot;InovuaReactDataGrid__cell InovuaReactDataGrid__cell--unlocked InovuaReactDataGrid__cell--direction-ltr InovuaReactDataGrid__cell--user-select-none InovuaReactDataGrid__cell--first InovuaReactDataGrid__cell--first-in-section InovuaReactDataGrid__cell--show-border-bottom InovuaReactDataGrid__cell--active-row-left-border&quot;]</value>
      <webElementGuid>7434c10a-db28-44d2-9a03-cd502da69264</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/section/main/div/div/div/div[2]/div/div/div[2]/div/div/div/div/div/div/div/div/div</value>
      <webElementGuid>80ea0621-28f8-414d-b958-28b8cbbbb228</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Operator'])[1]/following::div[16]</value>
      <webElementGuid>1a849658-57ac-45f8-b10c-48b71034bc80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jumlah'])[1]/following::div[28]</value>
      <webElementGuid>4afed9cf-534a-4fb0-88ec-12836f4dc622</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TESSS TIM IT'])[1]/preceding::div[4]</value>
      <webElementGuid>8280b78a-b8f4-494d-bca3-0eb211fddd71</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/div/div/div/div/div/div/div/div/div</value>
      <webElementGuid>5541f14a-149d-4252-90a7-2161a62f0fe4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'OH070923004' or . = 'OH070923004')]</value>
      <webElementGuid>b8934348-3700-440f-9f05-fc7952a7eefe</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
