<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Konfirmasi Batal PackingApakah Anda yak_0e89ce</name>
   <tag></tag>
   <elementGuidId>32fe7378-2650-4117-af22-4fe3ab6e3f0c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/section/main/div/div[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div._backDrop_xj5w5_1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>7817a0ec-f355-4761-bc48-c2549162ced6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_backDrop_xj5w5_1</value>
      <webElementGuid>a359d6fe-6584-45a2-928d-3b61ec001c61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Konfirmasi Batal PackingApakah Anda yakin ingin membatalkan packing kain?Tidak (ESC)Ya (ENTER)</value>
      <webElementGuid>8e38a280-281e-4955-aff3-3610f4ce4aa9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/section[@class=&quot;ant-layout layout css-p8cx3h&quot;]/main[@class=&quot;ant-layout-content&quot;]/div[@class=&quot;site-layout-content&quot;]/div[@class=&quot;_backDrop_xj5w5_1&quot;]</value>
      <webElementGuid>c00b025d-1856-4ecf-bea5-b8e6513398e7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/section/main/div/div[3]</value>
      <webElementGuid>9adfba68-0601-40ac-98d8-2333f0526368</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Loading'])[1]/following::div[2]</value>
      <webElementGuid>7a64cbef-95c2-4873-9f9c-b47f60bc5dec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='COKLAT SUSU'])[1]/following::div[21]</value>
      <webElementGuid>1aa12c8b-c8a1-42bb-b4eb-398189a04e56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]</value>
      <webElementGuid>08f79691-add2-4a12-820e-b35fe7448b26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Konfirmasi Batal PackingApakah Anda yakin ingin membatalkan packing kain?Tidak (ESC)Ya (ENTER)' or . = 'Konfirmasi Batal PackingApakah Anda yakin ingin membatalkan packing kain?Tidak (ESC)Ya (ENTER)')]</value>
      <webElementGuid>2d439ab2-a72b-48f3-bbb2-2729117ee99d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
