<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Verifikasi KainNo RollKode VerifikasiBa_326777</name>
   <tag></tag>
   <elementGuidId>1277773e-5e68-4dc6-b957-0c62c1851193</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div._containerModal_xj5w5_29</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/section/main/div/div[4]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>ed49f814-e26d-4389-80a5-d8c9f6b3b7e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_containerModal_xj5w5_29</value>
      <webElementGuid>1a539020-2984-48d9-8810-71bfa69399a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Verifikasi KainNo RollKode VerifikasiBatal (ESC)Verifikasi (ENTER)</value>
      <webElementGuid>0b08617e-851a-41a0-aeb8-e58d37176fd9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/section[@class=&quot;ant-layout layout css-p8cx3h&quot;]/main[@class=&quot;ant-layout-content&quot;]/div[@class=&quot;site-layout-content&quot;]/div[@class=&quot;_backDrop_xj5w5_1&quot;]/div[@class=&quot;_containerModal_xj5w5_29&quot;]</value>
      <webElementGuid>a4d7540b-ecf8-4b84-9f43-8b5568a3f4c5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/section/main/div/div[4]/div</value>
      <webElementGuid>e700957a-d0ec-4a92-a04c-39edd6a3ddf6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Loading'])[2]/following::div[3]</value>
      <webElementGuid>f7b86ad4-9597-4549-ac91-7f59ad0a68e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No records available'])[1]/following::div[18]</value>
      <webElementGuid>3ed4d09b-7541-4d55-b691-1f9a2048e280</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div</value>
      <webElementGuid>d3ec0e3b-4929-406b-aee4-4fa2f83e4eb1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Verifikasi KainNo RollKode VerifikasiBatal (ESC)Verifikasi (ENTER)' or . = 'Verifikasi KainNo RollKode VerifikasiBatal (ESC)Verifikasi (ENTER)')]</value>
      <webElementGuid>34ad3705-13b9-434f-9bbe-520d017f60b2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
