<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Batal (ESC)Verifikasi (ENTER)</name>
   <tag></tag>
   <elementGuidId>94ebc196-3115-40c3-93c2-66e115787b77</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div._bottom_xj5w5_78</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/section/main/div/div[4]/div/div[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>e067120e-66f0-496a-99f9-e37004644e4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_bottom_xj5w5_78</value>
      <webElementGuid>1e5585fd-5edb-4431-bb4a-375c141f99b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Batal (ESC)Verifikasi (ENTER)</value>
      <webElementGuid>0353a5a7-c1aa-4bce-8ea8-d358b484746e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/section[@class=&quot;ant-layout layout css-p8cx3h&quot;]/main[@class=&quot;ant-layout-content&quot;]/div[@class=&quot;site-layout-content&quot;]/div[@class=&quot;_backDrop_xj5w5_1&quot;]/div[@class=&quot;_containerModal_xj5w5_29&quot;]/div[@class=&quot;_bottom_xj5w5_78&quot;]</value>
      <webElementGuid>d119b624-a7dc-41f5-b028-3de8a8f8c8b9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/section/main/div/div[4]/div/div[3]</value>
      <webElementGuid>2236ecf2-c924-4743-83bb-52ccd985a8d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kode Verifikasi'])[1]/following::div[1]</value>
      <webElementGuid>307ae5d6-26d3-4f29-b935-6bb178b48bbf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No Roll'])[2]/following::div[2]</value>
      <webElementGuid>6bc635a4-cced-4768-b30c-3418cb568788</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div[3]</value>
      <webElementGuid>a976240e-5b3f-446d-99b5-dd04a85266f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Batal (ESC)Verifikasi (ENTER)' or . = 'Batal (ESC)Verifikasi (ENTER)')]</value>
      <webElementGuid>964b4ab0-3aae-456c-aacc-d11609fe8470</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
